apiVersion: v1
kind: Service
metadata:
  name: {{ include "traccar.fullname" . }}
  labels:
{{ include "traccar.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
    - port: 5055
      targetPort: 5055
      protocol: TCP
      name: http-android
    {{- range untilStep 5001 5003 1 }}
    - port: {{ . }}
      name: traccar-{{ . }}
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "traccar.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
