## Rocket Chat image version
## ref: https://hub.docker.com/r/rocketchat/rocket.chat/tags
##
rocketchat:
  image:
    repository: docker.io/rocketchat/rocket.chat
    tag: 1.3.1
    pullPolicy: IfNotPresent

  ##
  ## MongoDB chart configuration
  ### ref https://github.com/helm/charts/tree/master/stable/mongodb#configuration
  ##
  mongodb:
    ## Enable or disable MongoDB dependency completely.
    enabled: true

    mongodbRootPassword: some-super-secure-root-password-that-is-probablynever-used
    # todo: passwords
    mongodbUsername: rocketchat
    mongodbPassword: some-random-mongodb-password-for-rocketchat
    mongodbDatabase: rocketchat

    persistence:
      enabled: false
      ## mongodb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: false
    ## rocketchat data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi

  ## Configure the ingress object to hook into existing infastructure
  ### ref : http://kubernetes.io/docs/user-guide/ingress/
  ###
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: "nginx"
    path: /
    tls:
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
