apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "texas-logging.fullname" . }}
  labels:
{{ include "texas-logging.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "texas-logging.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "texas-logging.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{/*      initContainers:*/}}
{{/*        - name: init-couchdb*/}}
{{/*          image: curlimages/curl*/}}
{{/*          command: ['sh', '-c', 'until curl -s -k {{.Release.Name}}-couchdb.{{.Release.Namespace}}.svc.cluster.local:5984 | grep "Welcome"; do echo waiting for {{.Release.Name}}-couchdb.{{.Release.Namespace}}.svc.cluster.local; sleep 2; done;']*/}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-texas-configmap
            - secretRef:
                name: {{.Release.Name}}-couchdb
            - secretRef:
                name: {{.Release.Name}}-rabbitmq-ha
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
