apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "texas-service.fullname" . }}
  labels:
{{ include "texas-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "texas-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "texas-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: http
          env:
          - name: RABBIT_ADDRESS
            value: {{.Release.Name}}-rabbitmq-ha.{{.Release.Namespace}}.svc.cluster.local
          - name: RABBIT_USER
            valueFrom:
              secretKeyRef:
                name: {{.Release.Name}}-rabbitmq-ha
                key: rabbitmq-username
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Release.Name}}-rabbitmq-ha
                key: rabbitmq-password
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-texas-configmap
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
