{{/*apiVersion: v1*/}}
{{/*kind: ServiceAccount*/}}
{{/*metadata:*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*  name: {{ template "traefik.fullname" . }}*/}}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: traefik
  labels:
    app: traefik

spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: {{ template "traefik.fullname" . }}
      containers:
        - name: traefik
          image: traefik:v2.0.4
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/traefik/conf/
              name: traefik-volume
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:443
            - --entrypoints.amqp.Address=:5672
{{/*            {{- range untilStep (.Values.serverConfig.traccarStartPort|int) (.Values.serverConfig.traccarEndPort|int) 1 }}*/}}
            {{- range untilStep 5001 5003 1 }}
            - --entrypoints.traccar{{ . }}.Address=:{{ . }}
             {{- end }}
            - --providers.kubernetescrd
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email=texas@consilium.technology
            - --certificatesresolvers.default.acme.storage=acme.json
{{/*            - --configFile=/opt/traefik/conf/traefik-dynamic-config.yaml*/}}
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line asltogether.
            - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: websecure
              containerPort: 443
            - name: web
              containerPort: 8000
            - name: admin
              containerPort: 8080
            - name: amqp
              containerPort: 5672
{{/*            {{- range untilStep (.Values.serverConfig.traccarStartPort|int) (.Values.serverConfig.traccarEndPort|int) 1 }}*/}}
            {{- range untilStep 5001 5003 1 }}
            - name: traccar{{ . }}
              containerPort: {{ . }}
            {{- end }}
      volumes:
        - name: traefik-volume
          configMap:
            name: {{.Release.Name}}-traefik-dynamic-config
